local druidMacros = {
  ["Frenzied Regen"] = "#showtooltip Frenzied Regeneration\n/cast [stance:1] Frenzied Regeneration; !Bear Form",
  ["Demo Roar"] = "#showtooltip Demoralizing Roar\n/cast [stance:1] Demoralizing Roar; !Bear Form",
  ["Faerie Fire"] = "#showtooltip Faerie Fire\n/cast [nostance] Faerie Fire\n/cast [stance:1/3] Faerie Fire (Feral)\n/cast [stance:2/4/5/6] Faerie Fire",
  ["Dash"] = "#showtooltip Dash\n/cast [stance:3] Dash; !Cat Form",
  ["Stampeding Roar"] = "#showtooltip Stampeding Roar\n/cast [stance:1] Stampeding Roar(Bear Form); [stance:3] Stampeding Roar(Cat Form); !Bear Form",
  ["Maim"] = "#showtooltip Maim\n/startattack\n/cast [stance:3] Maim; !Cat Form",
  ["Skull Bash"] = "#showtooltip Skull Bash\n/cast [stance:1] Enrage\n/cast [stance:1] Skull Bash(Bear Form); [stance:3] Skull Bash(Cat Form); !Bear Form",
  ["Bash"] = "#showtooltip Bash\n/cast Enrage\n/cast [stance:1] Bash; !Bear Form",
  ["Prowl"] = "#showtooltip Prowl\n/cast [nostealth,stance:3] !Prowl; [stealth,stance:3] Pounce; !Cat Form",
  ["Challenging Roar"] = "#showtooltip Challenging Roar\n/cast [stance:1] Challenging Roar; !Bear Form",
  ["Hurricane"] = "#showtooltip Hurricane\n/cast !Hurricane",
  ["Wild Mushroom"] = "#showtooltip Wild Mushroom\n/cast !Wild Mushroom",
  ["Force of Nature"] = "#showtooltip Force of Nature\n/cast !Force of Nature",
}

local druidBindings = {
  ["`"] = "MACRO Bash",
  ["1"] = "SPELL Wrath",
  ["2"] = "SPELL Starfire",
  ["3"] = "MACRO Faerie Fire",
  ["4"] = "MACRO Dash",
  ["5"] = "MACRO Demo Roar",
  ["6"] = "SPELL Growl",
  ["C"] = "SPELL Healing Touch",
  ["E"] = "MACRO Skull Bash",
  ["F"] = "SPELL Cyclone",
  ["H"] = "SPELL Tranquility",
  ["Q"] = "SPELL Lifebloom",
  ["T"] = "SPELL Travel Form",
  ["V"] = "SPELL Regrowth",
  ["X"] = "SPELL Nourish",
  ["Z"] = "SPELL Entangling Roots",
  ["CTRL-4"] = "MACRO Hurricane",
  ["CTRL-A"] = "SPELL Soothe",
  ["CTRL-E"] = "SPELL Cat Form",
  ["CTRL-G"] = "SPELL Mark of the Wild",
  ["CTRL-Q"] = "SPELL Bear Form",
  ["CTRL-R"] = "SPELL Innervate",
  ["CTRL-S"] = "SPELL Hibernate",
  ["CTRL-W"] = "SPELL Rebirth",
  ["CTRL-X"] = "SPELL Claw",
  ["SHIFT-1"] = "MACRO Challenging Roar",
  ["SHIFT-2"] = "SPELL Remove Corruption",
  ["SHIFT-3"] = "MACRO Stampeding Roar",
  ["SHIFT-3"] = "MACRO Stampeding Roar",
  ["SHIFT-4"] = "SPELL Thorns",
  ["SHIFT-5"] = "SPELL Aquatic Form",
  ["SHIFT-A"] = "MACRO Prowl",
  ["SHIFT-C"] = "SPELL Rejuvenation",
  ["SHIFT-D"] = "SPELL Moonfire",
  ["SHIFT-F"] = "SPELL Nature's Grasp",
  ["SHIFT-G"] = "MACRO Wild Mushroom",
  ["SHIFT-H"] = "SPELL Swift Flight Form",
  ["SHIFT-L"] = "SPELL Revive",
  ["SHIFT-S"] = "SPELL Insect Swarm",
  ["SHIFT-T"] = "SPELL Wild Mushroom: Detonate",
  ["SHIFT-V"] = "MACRO Maim",
  ["SHIFT-X"] = "MACRO Frenzied Regen",
  ["SHIFT-Z"] = "SPELL Barkskin",
}

local druidFeralBindings = {
  ["="] = "SPELL Wrath",
  ["Q"] = "MACRO Ravage",
  ["R"] = "MACRO Maul",
  ["X"] = "MACRO Swipe",
  ["CTRL-C"] = "SPELL Moonfire",
  ["CTRL-F"] = "MACRO Feral Charge",
  ["SHIFT-C"] = "SPELL Survival Instincts",
  ["SHIFT-D"] = "MACRO Thrash",
  ["SHIFT-E"] = "MACRO Savage Roar",
  ["SHIFT-Q"] = "SPELL Berserk",
  ["SHIFT-R"] = "MACRO Enrage",
  ["SHIFT-S"] = "MACRO Rake",
}

local druidRestoBindings = {
  ["R"] = "SPELL Swiftmend",
  ["CTRL-F"] = "SPELL Wild Growth",
  ["SHIFT-E"] = "SPELL Nature's Swiftness",
  ["SHIFT-Q"] = "SPELL Tree of Life",
  ["SHIFT-R"] = "MACRO NS HT",
}

local druidBalanceBindings = {
  ["R"] = "SPELL Starsurge",
  ["CTRL-D"] = "MACRO Force of Nature",
  ["CTRL-F"] = "SPELL Starfall",
  ["SHIFT-E"] = "SPELL Typhoon",
  ["SHIFT-Q"] = "SPELL Moonkin Form",
  ["SHIFT-R"] = "SPELL Solar Beam",
}
