local paladinBindings = {
  ["`"] = "SPELL Hammer of Justice",
  ["2"] = "SPELL Crusader Strike",
  ["4"] = "SPELL Judgement",
  ["6"] = "SPELL Hand of Reckoning",
  ["C"] = "SPELL Divine Light",
  ["E"] = "SPELL Rebuke",
  ["H"] = "SPELL Holy Radiance",
  ["Q"] = "SPELL Word of Glory",
  ["T"] = "SPELL Hand of Freedom",
  ["V"] = "SPELL Flash of Light",
  ["X"] = "SPELL Holy Light",
  ["Z"] = "SPELL Seal of Justice",
  ["CTRL-4"] = "SPELL Holy Wrath",
  ["CTRL-A"] = "SPELL Seal of Righteousness",
  ["CTRL-C"] = "SPELL Crusader Aura",
  ["CTRL-E"] = "SPELL Righteous Fury",
  ["CTRL-G"] = "SPELL Blessing of Kings",
  ["CTRL-Q"] = "SPELL Seal of Insight",
  ["CTRL-R"] = "SPELL Divine Plea",
  ["CTRL-S"] = "SPELL Turn Evil",
  ["CTRL-W"] = "SPELL Concentration Aura",
  ["CTRL-X"] = "SPELL Seal of Truth",
  ["SHIFT-2"] = "SPELL Cleanse",
  ["SHIFT-3"] = "SPELL Avenging Wrath",
  ["SHIFT-4"] = "SPELL Consecration",
  ["SHIFT-5"] = "SPELL Devotion Aura",
  ["SHIFT-A"] = "SPELL Righteous Defense",
  ["SHIFT-C"] = "SPELL Lay on Hands",
  ["SHIFT-D"] = "SPELL Hand of Protection",
  ["SHIFT-E"] = "SPELL Cleanse",
  ["SHIFT-F"] = "SPELL Guardian of Ancient Kings",
  ["SHIFT-G"] = "SPELL Blessing of Might",
  ["SHIFT-H"] = "SPELL Resistance Aura",
  ["SHIFT-L"] = "SPELL Redemption",
  ["SHIFT-Q"] = "SPELL Inquisition",
  ["SHIFT-R"] = "SPELL Hand of Sacrifice",
  ["SHIFT-S"] = "SPELL Hand of Salvation",
  ["SHIFT-T"] = "SPELL Retribution Aura",
  ["SHIFT-V"] = "SPELL Hammer of Wrath",
  ["SHIFT-X"] = "SPELL Divine Shield",
  ["SHIFT-Z"] = "SPELL Divine Protection",
}

local paladinRetributionBindings = {
  ["1"] = "SPELL Exorcism",
  ["3"] = "SPELL Divine Storm",
  ["F"] = "SPELL Repentance",
  ["R"] = "SPELL Templar's Verdict",
  ["CTRL-F"] = "SPELL Zealotry",
}

local paladinProtectionBindings = {
  ["1"] = "SPELL Hammer of the Righteous",
  ["3"] = "SPELL Ardent Defender",
  ["F"] = "SPELL Avenger's Shield",
  ["R"] = "SPELL Shield of the Righteous",
  ["CTRL-F"] = "SPELL Divine Guardian",
}

local paladinHolyBindings = {
  ["1"] = "SPELL Exorcism",
  ["3"] = "SPELL Divine Favor",
  ["5"] = "SPELL Beacon of Light",
  ["F"] = "SPELL Aura Mastery",
  ["R"] = "SPELL Holy Shock",
  ["CTRL-F"] = "SPELL Light of Dawn",
}
