local warriorMacros = {
  ["Hamstring"] = "#showtooltip Hamstring\n/cast [stance:1/3] Hamstring; [stance:2] Battle Stance",
  ["Shield Wall"] = "#showtooltip Shield Wall\n/cast [stance:2,equipped:shields] Shield Wall; [stance:1/3] Defensive Stance\n/stopmacro [equipped:shields]\n/equip YOUR 1H\n/equip YOUR SHIELD",
  ["Shield Block"] = "#showtooltip Shield Block\n/cast [stance:2,equipped:shields] Shield Block; [stance:1/3] Defensive Stance\n/stopmacro [equipped:shields]\n/equip YOUR 1H\n/equip YOUR SHIELD",
  ["Spell Reflection"] = "#showtooltip Spell Reflection\n/cast [stance:1/2,equipped:shields] Spell Reflection; [stance:3] Battle Stance\n/stopmacro [equipped:shields]\n/equip YOUR 1H\n/equip YOUR SHIELD",
  ["Thunder Clap"] = "#showtooltip Thunder Clap\n/cast [stance:1/2] Thunder Clap; [stance:3] Battle Stance",
  ["Whirlwind"] = "#showtooltip Whirlwind\n/startattack\n/cast [stance:3] Whirlwind; [stance:1/2] Berserker Stance",
  ["Enraged Regen"] = "#showtooltip Enraged Regeneration\n/cast Berserker Rage\n/cast Enraged Regeneration",
  ["Disarm"] = "#showtooltip Disarm\n/cast [stance:2] Disarm; [stance:1/3] Defensive Stance",
  ["Revenge"] = "#showtooltip Revenge\n/startattack\n/cast [stance:2] Revenge; [stance:1/3] Defensive Stance",
  ["Shattering Throw"] = "#showtooltip Shattering Throw\n/cast [stance:1] Shattering Throw; [stance:2/3] Battle Stance",
  ["Colossus Smash"] = "#showtooltip Colossus Smash\n/startattack\n/cast [stance:1/3] Colossus Smash; [stance:2] Battle Stance",
  ["Recklessness"] = "#showtooltip Recklessness\n/cast [stance:3] Recklessness; [stance:1/2] Berserker Stance",
  ["Overpower"] = "#showtooltip Overpower\n/startattack\n/cast [stance:1] Overpower; [stance:2/3] Battle Stance",
  ["Rend"] = "#showtooltip Rend\n/startattack\n/cast [stance:1/2] Rend; [stance:3] Battle Stance",
  ["Taunt"] = "#showtooltip Taunt\n/startattack\n/cast [stance:2] Taunt; [stance:1/3] Defensive Stance",
  ["Pummel"] = "#showtooltip Pummel\n/cast [stance:1/2,equipped:shields] Shield Bash;[stance:2,noequipped:shields] Battle Stance\n/cast [stance:1/3] Pummel",
  ["Retaliation"] = "#showtooltip Retaliation\n/cast [stance:1] Retaliation; [stance:2/3] Battle Stance",
}

local warriorBindings = {
  ["3"] = "MACRO Colossus Smash",
  ["4"] = "SPELL Heroic Strike",
  ["5"] = "SPELL Heroic Throw",
  ["6"] = "MACRO Taunt",
  ["E"] = "MACRO Pummel",
  ["F"] = "MACRO Heroic Leap",
  ["H"] = "SPELL Sweeping Strikes",
  ["Q"] = "SPELL Berserker Rage",
  ["R"] = "MACRO Disarm",
  ["V"] = "MACRO Enraged Regen",
  ["Z"] = "MACRO Hamstring",
  ["CTRL-4"] = "MACRO Whirlwind",
  ["CTRL-A"] = "SPELL Cleave",
  ["CTRL-C"] = "MACRO Retaliation",
  ["CTRL-E"] = "SPELL Defensive Stance",
  ["CTRL-F"] = "SPELL Bladestorm",
  ["CTRL-G"] = "SPELL Berserker Stance",
  ["CTRL-Q"] = "SPELL Battle Stance",
  ["CTRL-R"] = "SPELL Challenging Shout",
  ["CTRL-S"] = "MACRO 2h",
  ["CTRL-V"] = "SPELL Victory Rush",
  ["CTRL-X"] = "MACRO Shattering Throw",
  ["SHIFT-1"] = "SPELL Inner Rage",
  ["SHIFT-2"] = "SPELL Demoralizing Shout",
  ["SHIFT-4"] = "MACRO Thunder Clap",
  ["SHIFT-A"] = "SPELL Battle Shout",
  ["SHIFT-C"] = "MACRO Spell Reflection",
  ["SHIFT-E"] = "MACRO Overpower",
  ["SHIFT-F"] = "SPELL Intimidating Shout",
  ["SHIFT-G"] = "SPELL Commanding Shout",
  ["SHIFT-Q"] = "MACRO Recklessness",
  ["SHIFT-R"] = "MACRO Revenge",
  ["SHIFT-S"] = "MACRO Rend",
  ["SHIFT-V"] = "SPELL Execute",
  ["SHIFT-X"] = "MACRO Shield Block",
  ["SHIFT-Z"] = "MACRO Shield Wall",
}

local warriorProtectionBindings = {
  ["`"] = "SPELL Concussion Blow",
  ["1"] = "SPELL Devastate",
  ["2"] = "SPELL Shield Slam",
  ["C"] = "SPELL Intercept",
  ["H"] = "SPELL Last Stand",
  ["T"] = "SPELL Intervene",
  ["X"] = "SPELL Charge",
  ["SHIFT-3"] = "SPELL Devastate",
  ["SHIFT-D"] = "SPELL Shockwave",
  ["SHIFT-T"] = "SPELL Vigilance",
}

local warriorFuryBindings = {
  ["`"] = "MACRO Raging Blow",
  ["1"] = "SPELL Bloodthirst",
  ["2"] = "SPELL Slam",
  ["C"] = "MACRO Intercept",
  ["H"] = "SPELL Heroic Fury",
  ["T"] = "MACRO Intervene",
  ["X"] = "MACRO Charge",
  ["SHIFT-3"] = "SPELL Death Wish",
  ["SHIFT-D"] = "SPELL Sunder Armor",
  ["SHIFT-T"] = "SPELL Piercing Howl",
}

local warriorArmsBindings = {
  ["`"] = "MACRO Throwdown",
  ["1"] = "SPELL Mortal Strike",
  ["2"] = "SPELL Slam",
  ["C"] = "MACRO Intercept",
  ["H"] = "SPELL Sweeping Strikes",
  ["T"] = "MACRO Intervene",
  ["X"] = "MACRO Charge",
  ["CTRL-F"] = "SPELL Bladestorm",
  ["SHIFT-3"] = "SPELL Deadly Calm",
  ["SHIFT-D"] = "SPELL Sunder Armor",
  ["SHIFT-T"] = "SPELL Piercing Howl",
}
